"""
AUTO-GENERATED by verify_from_dailymed.py — do not hand-edit.

Every value below was extracted verbatim from an FDA Structured Product
Label on DailyMed, with its source URL and retrieval date. Regenerate by
rerunning the script; do not add entries manually.
"""

GENERATED_AT = "2026-08-03T09:25:48.440315+00:00"

DAILYMED_FACTS = {
    "acarbose": {
        "molecule": "Acarbose",
        "facts": {
            "recommended_dosage": {
                "value": "The recommended starting dosage of acarbose tablets is 25 mg given orally three times daily at the start (with the first bite) of each main meal.",
                "source_name": "FDA prescribing information via DailyMed (ACARBOSE TABLET [BRYANT RANCH PREPACK])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=067c0adc-7322-489d-9baa-1d061b37be36",
                "retrieved": "2026-08-03",
                "quote": "The recommended starting dosage of acarbose tablets is 25 mg given orally three times daily at the start (with the first bite) of each main meal."
            }
        },
        "spl_setid": "067c0adc-7322-489d-9baa-1d061b37be36",
        "spl_title": "ACARBOSE TABLET [BRYANT RANCH PREPACK]"
    },
    "alirocumab": {
        "molecule": "Alirocumab",
        "facts": {
            "us_initial_approval_year": {
                "value": 2015,
                "source_name": "FDA prescribing information via DailyMed (PRALUENT (ALIROCUMAB) INJECTION, SOLUTION [SANOFI-AVENTIS U.S. LLC])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=446f6b5c-0dd4-44ff-9bc2-c2b41f2806b4",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 2015"
            },
            "recommended_dosage": {
                "value": "The recommended starting dosage of PRALUENT is either 75 mg once every 2 weeks or 300 mg once every 4 weeks administered subcutaneously.",
                "source_name": "FDA prescribing information via DailyMed (PRALUENT (ALIROCUMAB) INJECTION, SOLUTION [SANOFI-AVENTIS U.S. LLC])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=446f6b5c-0dd4-44ff-9bc2-c2b41f2806b4",
                "retrieved": "2026-08-03",
                "quote": "The recommended starting dosage of PRALUENT is either 75 mg once every 2 weeks or 300 mg once every 4 weeks administered subcutaneously."
            }
        },
        "spl_setid": "446f6b5c-0dd4-44ff-9bc2-c2b41f2806b4",
        "spl_title": "PRALUENT (ALIROCUMAB) INJECTION, SOLUTION [SANOFI-AVENTIS U.S. LLC]"
    },
    "allopurinol": {
        "molecule": "Allopurinol",
        "facts": {
            "us_initial_approval_year": {
                "value": 1966,
                "source_name": "FDA prescribing information via DailyMed (ALLOPURINOL TABLET [CARDINAL HEALTH 107, LLC])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b6c5b5c0-b1cb-44c0-a849-5d317e6fa300",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval:1966"
            },
            "recommended_dosage": {
                "value": "The recommended dosage is: o Adults: 300 mg to 800 mg orally daily.",
                "source_name": "FDA prescribing information via DailyMed (ALLOPURINOL TABLET [CARDINAL HEALTH 107, LLC])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b6c5b5c0-b1cb-44c0-a849-5d317e6fa300",
                "retrieved": "2026-08-03",
                "quote": "The recommended dosage is: o Adults: 300 mg to 800 mg orally daily."
            }
        },
        "spl_setid": "b6c5b5c0-b1cb-44c0-a849-5d317e6fa300",
        "spl_title": "ALLOPURINOL TABLET [CARDINAL HEALTH 107, LLC]"
    },
    "alteplase (rtpa)": {
        "molecule": "Alteplase (rtPA)",
        "facts": {
            "us_initial_approval_year": {
                "value": 1987,
                "source_name": "FDA prescribing information via DailyMed (ACTIVASE (ALTEPLASE) KIT [GENENTECH, INC.])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c669f77c-fa48-478b-a14b-80b20a0139c2",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 1987"
            },
            "recommended_dosage": {
                "value": "The recommended dose is 0.9 mg/kg (not to exceed 90 mg total dose) infused intravenously over 60 minutes with 10% of the total dose administered as an initial bolus over 1 minute.",
                "source_name": "FDA prescribing information via DailyMed (ACTIVASE (ALTEPLASE) KIT [GENENTECH, INC.])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c669f77c-fa48-478b-a14b-80b20a0139c2",
                "retrieved": "2026-08-03",
                "quote": "The recommended dose is 0.9 mg/kg (not to exceed 90 mg total dose) infused intravenously over 60 minutes with 10% of the total dose administered as an initial bolus over 1 minute."
            }
        },
        "spl_setid": "c669f77c-fa48-478b-a14b-80b20a0139c2",
        "spl_title": "ACTIVASE (ALTEPLASE) KIT [GENENTECH, INC.]"
    },
    "canagliflozin": {
        "molecule": "Canagliflozin",
        "facts": {
            "us_initial_approval_year": {
                "value": 2013,
                "source_name": "FDA prescribing information via DailyMed (INVOKANA (CANAGLIFLOZIN) TABLET, FILM COATED [JANSSEN PHARMACEUTICALS, INC.])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b9057d3b-b104-4f09-8a61-c61ef9d4a3f3",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 2013"
            },
            "recommended_dosage": {
                "value": "The recommended starting dosage in adults and pediatric patients aged 10 years and older with type 2 diabetes mellitus is 100 mg orally once daily, taken before the first meal of the day to improve glycemic control.",
                "source_name": "FDA prescribing information via DailyMed (INVOKANA (CANAGLIFLOZIN) TABLET, FILM COATED [JANSSEN PHARMACEUTICALS, INC.])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b9057d3b-b104-4f09-8a61-c61ef9d4a3f3",
                "retrieved": "2026-08-03",
                "quote": "The recommended starting dosage in adults and pediatric patients aged 10 years and older with type 2 diabetes mellitus is 100 mg orally once daily, taken before the first meal of the day to improve glycemic control."
            }
        },
        "spl_setid": "b9057d3b-b104-4f09-8a61-c61ef9d4a3f3",
        "spl_title": "INVOKANA (CANAGLIFLOZIN) TABLET, FILM COATED [JANSSEN PHARMACEUTICALS, INC.]"
    },
    "clopidogrel": {
        "molecule": "Clopidogrel",
        "facts": {
            "us_initial_approval_year": {
                "value": 1997,
                "source_name": "FDA prescribing information via DailyMed (CLOPIDOGREL (CLOPIDOGREL BISULFATE) TABLET, FILM COATED [PREFERRED PHARMACEUTICALS INC.])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c9928956-bb7b-4ec2-bc38-d3c9c4199cae",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 1997"
            }
        },
        "spl_setid": "c9928956-bb7b-4ec2-bc38-d3c9c4199cae",
        "spl_title": "CLOPIDOGREL (CLOPIDOGREL BISULFATE) TABLET, FILM COATED [PREFERRED PHARMACEUTICALS INC.]"
    },
    "clotrimazole (vaginal)": {
        "molecule": "Clotrimazole (vaginal)",
        "facts": {
            "us_initial_approval_year": {
                "value": 1984,
                "source_name": "FDA prescribing information via DailyMed (CLOTRIMAZOLE AND BETAMETHASONE DIPROPIONATE CREAM [E. FOUGERA & CO. A DIVISION OF FOUGERA PHARMACEUTICALS, LLC])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=55db730a-df6d-4950-9c26-91b06bdcef36",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 1984"
            }
        },
        "spl_setid": "55db730a-df6d-4950-9c26-91b06bdcef36",
        "spl_title": "CLOTRIMAZOLE AND BETAMETHASONE DIPROPIONATE CREAM [E. FOUGERA & CO. A DIVISION OF FOUGERA PHARMACEUTICALS, LLC]"
    },
    "dabigatran": {
        "molecule": "Dabigatran",
        "facts": {
            "us_initial_approval_year": {
                "value": 2010,
                "source_name": "FDA prescribing information via DailyMed (DABIGATRAN (DABIGATRAN ETEXILATE) CAPSULE [AMERICAN HEALTH PACKAGING])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f7ea7e2c-ca54-4ecc-9fc7-bd3571b0ebc2",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 2010"
            }
        },
        "spl_setid": "f7ea7e2c-ca54-4ecc-9fc7-bd3571b0ebc2",
        "spl_title": "DABIGATRAN (DABIGATRAN ETEXILATE) CAPSULE [AMERICAN HEALTH PACKAGING]"
    },
    "digoxin": {
        "molecule": "Digoxin",
        "facts": {
            "us_initial_approval_year": {
                "value": 1954,
                "source_name": "FDA prescribing information via DailyMed (DIGOXIN TABLET [BRYANT RANCH PREPACK])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e61d2108-d871-44c0-b12a-2e61fbb56967",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 1954"
            }
        },
        "spl_setid": "e61d2108-d871-44c0-b12a-2e61fbb56967",
        "spl_title": "DIGOXIN TABLET [BRYANT RANCH PREPACK]"
    },
    "dronedarone": {
        "molecule": "Dronedarone",
        "facts": {
            "us_initial_approval_year": {
                "value": 2009,
                "source_name": "FDA prescribing information via DailyMed (MULTAQ (DRONEDARONE) TABLET, FILM COATED [SANOFI-AVENTIS U.S. LLC])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7fa41601-7fb5-4155-8e50-2ae903f0d2d6",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 2009"
            },
            "recommended_dosage": {
                "value": "The recommended dosage of MULTAQ is 400 mg twice daily in adults.",
                "source_name": "FDA prescribing information via DailyMed (MULTAQ (DRONEDARONE) TABLET, FILM COATED [SANOFI-AVENTIS U.S. LLC])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7fa41601-7fb5-4155-8e50-2ae903f0d2d6",
                "retrieved": "2026-08-03",
                "quote": "The recommended dosage of MULTAQ is 400 mg twice daily in adults."
            }
        },
        "spl_setid": "7fa41601-7fb5-4155-8e50-2ae903f0d2d6",
        "spl_title": "MULTAQ (DRONEDARONE) TABLET, FILM COATED [SANOFI-AVENTIS U.S. LLC]"
    },
    "dulaglutide": {
        "molecule": "Dulaglutide",
        "facts": {
            "us_initial_approval_year": {
                "value": 2014,
                "source_name": "FDA prescribing information via DailyMed (TRULICITY (DULAGLUTIDE) INJECTION, SOLUTION [ELI LILLY AND COMPANY])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=463050bd-2b1c-40f5-b3c3-0a04bb433309",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 2014"
            },
            "recommended_dosage": {
                "value": "The recommended starting dosage of TRULICITY is 0.75 mg injected subcutaneously once weekly.",
                "source_name": "FDA prescribing information via DailyMed (TRULICITY (DULAGLUTIDE) INJECTION, SOLUTION [ELI LILLY AND COMPANY])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=463050bd-2b1c-40f5-b3c3-0a04bb433309",
                "retrieved": "2026-08-03",
                "quote": "The recommended starting dosage of TRULICITY is 0.75 mg injected subcutaneously once weekly."
            }
        },
        "spl_setid": "463050bd-2b1c-40f5-b3c3-0a04bb433309",
        "spl_title": "TRULICITY (DULAGLUTIDE) INJECTION, SOLUTION [ELI LILLY AND COMPANY]"
    },
    "edoxaban": {
        "molecule": "Edoxaban",
        "facts": {
            "us_initial_approval_year": {
                "value": 2015,
                "source_name": "FDA prescribing information via DailyMed (SAVAYSA (EDOXABAN TOSYLATE) TABLET, FILM COATED [DAIICHI SANKYO INC.])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e77d3400-56ad-11e3-949a-0800200c9a66",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 2015"
            },
            "recommended_dosage": {
                "value": "The recommended dose is 60 mg once daily in patients with CrCL &gt;50 to ≤ 95 mL/min.",
                "source_name": "FDA prescribing information via DailyMed (SAVAYSA (EDOXABAN TOSYLATE) TABLET, FILM COATED [DAIICHI SANKYO INC.])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e77d3400-56ad-11e3-949a-0800200c9a66",
                "retrieved": "2026-08-03",
                "quote": "The recommended dose is 60 mg once daily in patients with CrCL &gt;50 to ≤ 95 mL/min."
            }
        },
        "spl_setid": "e77d3400-56ad-11e3-949a-0800200c9a66",
        "spl_title": "SAVAYSA (EDOXABAN TOSYLATE) TABLET, FILM COATED [DAIICHI SANKYO INC.]"
    },
    "enoxaparin": {
        "molecule": "Enoxaparin",
        "facts": {
            "us_initial_approval_year": {
                "value": 1993,
                "source_name": "FDA prescribing information via DailyMed (LOVENOX (ENOXAPARIN SODIUM) INJECTION [SANOFI-AVENTIS U.S. LLC])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5017a927-2a24-4f27-89f9-27c805bf7d59",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 1993"
            },
            "recommended_dosage": {
                "value": "The recommended dose of Lovenox is 40 mg by subcutaneous injection once a day (with the initial dose given 2 hours prior to surgery) in patients undergoing abdominal surgery who are at risk for thromboembolic complications.",
                "source_name": "FDA prescribing information via DailyMed (LOVENOX (ENOXAPARIN SODIUM) INJECTION [SANOFI-AVENTIS U.S. LLC])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=5017a927-2a24-4f27-89f9-27c805bf7d59",
                "retrieved": "2026-08-03",
                "quote": "The recommended dose of Lovenox is 40 mg by subcutaneous injection once a day (with the initial dose given 2 hours prior to surgery) in patients undergoing abdominal surgery who are at risk for thromboembolic complications."
            }
        },
        "spl_setid": "5017a927-2a24-4f27-89f9-27c805bf7d59",
        "spl_title": "LOVENOX (ENOXAPARIN SODIUM) INJECTION [SANOFI-AVENTIS U.S. LLC]"
    },
    "ertugliflozin": {
        "molecule": "Ertugliflozin",
        "facts": {
            "us_initial_approval_year": {
                "value": 2017,
                "source_name": "FDA prescribing information via DailyMed (STEGLUJAN (ERTUGLIFLOZIN AND SITAGLIPTIN) TABLET, FILM COATED [MERCK SHARP & DOHME LLC])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c2c553d8-5a9d-4366-bf53-8bdb5a876d19",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 2017"
            },
            "recommended_dosage": {
                "value": "The recommended starting dosage of STEGLUJAN is 5 mg ertugliflozin/100 mg sitagliptin orally once daily, taken in the morning, with or without food.",
                "source_name": "FDA prescribing information via DailyMed (STEGLUJAN (ERTUGLIFLOZIN AND SITAGLIPTIN) TABLET, FILM COATED [MERCK SHARP & DOHME LLC])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c2c553d8-5a9d-4366-bf53-8bdb5a876d19",
                "retrieved": "2026-08-03",
                "quote": "The recommended starting dosage of STEGLUJAN is 5 mg ertugliflozin/100 mg sitagliptin orally once daily, taken in the morning, with or without food."
            }
        },
        "spl_setid": "c2c553d8-5a9d-4366-bf53-8bdb5a876d19",
        "spl_title": "STEGLUJAN (ERTUGLIFLOZIN AND SITAGLIPTIN) TABLET, FILM COATED [MERCK SHARP & DOHME LLC]"
    },
    "evolocumab": {
        "molecule": "Evolocumab",
        "facts": {
            "us_initial_approval_year": {
                "value": 2015,
                "source_name": "FDA prescribing information via DailyMed (REPATHA (EVOLOCUMAB) INJECTION, SOLUTION REPATHA (EVOLOCUMAB) KIT [AMGEN USA INC.])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=cd61e902-166d-4aa6-9f3c-a18c1008d07e",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 2015"
            },
            "recommended_dosage": {
                "value": "The recommended dosage of REPATHA is either 140 mg every 2 weeks OR 420 mg once monthly administered subcutaneously.",
                "source_name": "FDA prescribing information via DailyMed (REPATHA (EVOLOCUMAB) INJECTION, SOLUTION REPATHA (EVOLOCUMAB) KIT [AMGEN USA INC.])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=cd61e902-166d-4aa6-9f3c-a18c1008d07e",
                "retrieved": "2026-08-03",
                "quote": "The recommended dosage of REPATHA is either 140 mg every 2 weeks OR 420 mg once monthly administered subcutaneously."
            }
        },
        "spl_setid": "cd61e902-166d-4aa6-9f3c-a18c1008d07e",
        "spl_title": "REPATHA (EVOLOCUMAB) INJECTION, SOLUTION REPATHA (EVOLOCUMAB) KIT [AMGEN USA INC.]"
    },
    "follitropin alfa (recombinant fsh)": {
        "molecule": "Follitropin alfa (recombinant FSH)",
        "facts": {
            "us_initial_approval_year": {
                "value": 1997,
                "source_name": "FDA prescribing information via DailyMed (GONAL-F (FOLLITROPIN ALFA) KIT [EMD SERONO, INC.])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ae85b9c3-e7eb-4981-a5d9-346050e8f189",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 1997"
            }
        },
        "spl_setid": "ae85b9c3-e7eb-4981-a5d9-346050e8f189",
        "spl_title": "GONAL-F (FOLLITROPIN ALFA) KIT [EMD SERONO, INC.]"
    },
    "fondaparinux": {
        "molecule": "Fondaparinux",
        "facts": {
            "us_initial_approval_year": {
                "value": 2001,
                "source_name": "FDA prescribing information via DailyMed (FONDAPARINUX SODIUM INJECTION, SOLUTION [ZYDUS PHARMACEUTICALS (USA) INC.])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=dffbf7c9-495e-4a33-ac76-57b52f014fc2",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 2001"
            }
        },
        "spl_setid": "dffbf7c9-495e-4a33-ac76-57b52f014fc2",
        "spl_title": "FONDAPARINUX SODIUM INJECTION, SOLUTION [ZYDUS PHARMACEUTICALS (USA) INC.]"
    },
    "furosemide": {
        "molecule": "Furosemide",
        "facts": {
            "us_initial_approval_year": {
                "value": 1982,
                "source_name": "FDA prescribing information via DailyMed (FUROSEMIDE INJECTION [CIVICA, INC.])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6d9caaab-d874-4cf1-b9fe-408452a18998",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 1982"
            }
        },
        "spl_setid": "6d9caaab-d874-4cf1-b9fe-408452a18998",
        "spl_title": "FUROSEMIDE INJECTION [CIVICA, INC.]"
    },
    "glimepiride": {
        "molecule": "Glimepiride",
        "facts": {
            "us_initial_approval_year": {
                "value": 1995,
                "source_name": "FDA prescribing information via DailyMed (GLIMEPIRIDE TABLET [ST. MARY'S MEDICAL PARK PHARMACY])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=fc9d8495-184c-3af1-e053-6394a90a5e29",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 1995"
            }
        },
        "spl_setid": "fc9d8495-184c-3af1-e053-6394a90a5e29",
        "spl_title": "GLIMEPIRIDE TABLET [ST. MARY'S MEDICAL PARK PHARMACY]"
    },
    "goserelin": {
        "molecule": "Goserelin",
        "facts": {
            "us_initial_approval_year": {
                "value": 1989,
                "source_name": "FDA prescribing information via DailyMed (ZOLADEX (GOSERELIN) IMPLANT [TERSERA THERAPEUTICS LLC])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=294b168b-6e5f-4db9-bf70-d599271458b3",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 1989"
            }
        },
        "spl_setid": "294b168b-6e5f-4db9-bf70-d599271458b3",
        "spl_title": "ZOLADEX (GOSERELIN) IMPLANT [TERSERA THERAPEUTICS LLC]"
    },
    "inclisiran": {
        "molecule": "Inclisiran",
        "facts": {
            "us_initial_approval_year": {
                "value": 2021,
                "source_name": "FDA prescribing information via DailyMed (LEQVIO (INCLISIRAN) INJECTION, SOLUTION [NOVARTIS PHARMACEUTICALS CORPORATION])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6fc0afca-4513-4c35-b594-6544aee29a44",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 2021"
            },
            "recommended_dosage": {
                "value": "The recommended dosage of LEQVIO for adults and pediatric patients aged 12 years and older is 284 mg administered as a single subcutaneous injection initially, again at 3 months, and then every 6 months.",
                "source_name": "FDA prescribing information via DailyMed (LEQVIO (INCLISIRAN) INJECTION, SOLUTION [NOVARTIS PHARMACEUTICALS CORPORATION])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6fc0afca-4513-4c35-b594-6544aee29a44",
                "retrieved": "2026-08-03",
                "quote": "The recommended dosage of LEQVIO for adults and pediatric patients aged 12 years and older is 284 mg administered as a single subcutaneous injection initially, again at 3 months, and then every 6 months."
            },
            "dosing_schedule": {
                "value": "The recommended dosage of LEQVIO for adults and pediatric patients aged 12 years and older is 284 mg administered as a single subcutaneous injection initially, again at 3 months, and then every 6 months.",
                "source_name": "FDA prescribing information via DailyMed (LEQVIO (INCLISIRAN) INJECTION, SOLUTION [NOVARTIS PHARMACEUTICALS CORPORATION])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=6fc0afca-4513-4c35-b594-6544aee29a44",
                "retrieved": "2026-08-03",
                "quote": "The recommended dosage of LEQVIO for adults and pediatric patients aged 12 years and older is 284 mg administered as a single subcutaneous injection initially, again at 3 months, and then every 6 months.",
                "doses_year_1": 3,
                "doses_maintenance": 2
            }
        },
        "spl_setid": "6fc0afca-4513-4c35-b594-6544aee29a44",
        "spl_title": "LEQVIO (INCLISIRAN) INJECTION, SOLUTION [NOVARTIS PHARMACEUTICALS CORPORATION]"
    },
    "insulin aspart": {
        "molecule": "Insulin aspart",
        "facts": {
            "us_initial_approval_year": {
                "value": 2000,
                "source_name": "FDA prescribing information via DailyMed (INSULIN ASPART INJECTION, SOLUTION [NOVO NORDISK PHARMA, INC.])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=bee5b358-c863-420b-be73-ced2e920c499",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 2000"
            }
        },
        "spl_setid": "bee5b358-c863-420b-be73-ced2e920c499",
        "spl_title": "INSULIN ASPART INJECTION, SOLUTION [NOVO NORDISK PHARMA, INC.]"
    },
    "insulin degludec": {
        "molecule": "Insulin degludec",
        "facts": {
            "us_initial_approval_year": {
                "value": 2015,
                "source_name": "FDA prescribing information via DailyMed (INSULIN DEGLUDEC INJECTION, SOLUTION [NOVO NORDISK PHARMA, INC.])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c1be283d-4b1d-4996-b2a7-4488dbff3037",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 2015"
            }
        },
        "spl_setid": "c1be283d-4b1d-4996-b2a7-4488dbff3037",
        "spl_title": "INSULIN DEGLUDEC INJECTION, SOLUTION [NOVO NORDISK PHARMA, INC.]"
    },
    "insulin glargine": {
        "molecule": "Insulin glargine",
        "facts": {
            "us_initial_approval_year": {
                "value": 2016,
                "source_name": "FDA prescribing information via DailyMed (SOLIQUA 100/33 (INSULIN GLARGINE AND LIXISENATIDE) INJECTION, SOLUTION [SANOFI-AVENTIS U.S. LLC])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4bba538b-cf7c-4310-ae8f-cb711ed21bcc",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 2016"
            }
        },
        "spl_setid": "4bba538b-cf7c-4310-ae8f-cb711ed21bcc",
        "spl_title": "SOLIQUA 100/33 (INSULIN GLARGINE AND LIXISENATIDE) INJECTION, SOLUTION [SANOFI-AVENTIS U.S. LLC]"
    },
    "insulin glulisine": {
        "molecule": "Insulin glulisine",
        "facts": {
            "us_initial_approval_year": {
                "value": 2004,
                "source_name": "FDA prescribing information via DailyMed (APIDRA (INSULIN GLULISINE) INJECTION, SOLUTION APIDRA SOLOSTAR (INSULIN GLULISINE) INJECTION, SOLUTION [SANOFI-AVENTIS U.S. LLC])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=e7af6a7a-8046-4fb4-9979-4ec4230b23aa",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 2004"
            }
        },
        "spl_setid": "e7af6a7a-8046-4fb4-9979-4ec4230b23aa",
        "spl_title": "APIDRA (INSULIN GLULISINE) INJECTION, SOLUTION APIDRA SOLOSTAR (INSULIN GLULISINE) INJECTION, SOLUTION [SANOFI-AVENTIS U.S. LLC]"
    },
    "insulin lispro": {
        "molecule": "Insulin lispro",
        "facts": {
            "us_initial_approval_year": {
                "value": 1999,
                "source_name": "FDA prescribing information via DailyMed (HUMALOG MIX50/50 (INSULIN LISPRO) INJECTION, SUSPENSION HUMALOG MIX50/50 KWIKPEN (INSULIN LISPRO) INJECTION, SUSPENSION [ELI LILLY AND COMPANY])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=b34cd3ff-d0af-4852-b4ef-2a8b4a93aeae",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 1999"
            }
        },
        "spl_setid": "b34cd3ff-d0af-4852-b4ef-2a8b4a93aeae",
        "spl_title": "HUMALOG MIX50/50 (INSULIN LISPRO) INJECTION, SUSPENSION HUMALOG MIX50/50 KWIKPEN (INSULIN LISPRO) INJECTION, SUSPENSION [ELI LILLY AND COMPANY]"
    },
    "liraglutide": {
        "molecule": "Liraglutide",
        "facts": {
            "us_initial_approval_year": {
                "value": 2010,
                "source_name": "FDA prescribing information via DailyMed (SAXENDA (LIRAGLUTIDE) INJECTION, SOLUTION [NOVO NORDISK PHARMACEUTICAL INDUSTRIES, LP])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3946d389-0926-4f77-a708-0acb8153b143",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 2010"
            },
            "recommended_dosage": {
                "value": "The recommended dose of SAXENDA is 3 mg daily.",
                "source_name": "FDA prescribing information via DailyMed (SAXENDA (LIRAGLUTIDE) INJECTION, SOLUTION [NOVO NORDISK PHARMACEUTICAL INDUSTRIES, LP])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3946d389-0926-4f77-a708-0acb8153b143",
                "retrieved": "2026-08-03",
                "quote": "The recommended dose of SAXENDA is 3 mg daily."
            }
        },
        "spl_setid": "3946d389-0926-4f77-a708-0acb8153b143",
        "spl_title": "SAXENDA (LIRAGLUTIDE) INJECTION, SOLUTION [NOVO NORDISK PHARMACEUTICAL INDUSTRIES, LP]"
    },
    "liraglutide (saxenda)": {
        "molecule": "Liraglutide (Saxenda)",
        "facts": {
            "us_initial_approval_year": {
                "value": 2010,
                "source_name": "FDA prescribing information via DailyMed (SAXENDA (LIRAGLUTIDE) INJECTION, SOLUTION [NOVO NORDISK PHARMACEUTICAL INDUSTRIES, LP])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3946d389-0926-4f77-a708-0acb8153b143",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 2010"
            },
            "recommended_dosage": {
                "value": "The recommended dose of SAXENDA is 3 mg daily.",
                "source_name": "FDA prescribing information via DailyMed (SAXENDA (LIRAGLUTIDE) INJECTION, SOLUTION [NOVO NORDISK PHARMACEUTICAL INDUSTRIES, LP])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3946d389-0926-4f77-a708-0acb8153b143",
                "retrieved": "2026-08-03",
                "quote": "The recommended dose of SAXENDA is 3 mg daily."
            }
        },
        "spl_setid": "3946d389-0926-4f77-a708-0acb8153b143",
        "spl_title": "SAXENDA (LIRAGLUTIDE) INJECTION, SOLUTION [NOVO NORDISK PHARMACEUTICAL INDUSTRIES, LP]"
    },
    "medroxyprogesterone acetate (dmpa)": {
        "molecule": "Medroxyprogesterone acetate (DMPA)",
        "facts": {
            "us_initial_approval_year": {
                "value": 1959,
                "source_name": "FDA prescribing information via DailyMed (MEDROXYPROGESTERONE ACETATE INJECTION, SUSPENSION [PRASCO LABORATORIES])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=987496bf-b4b0-409b-b745-f52ed0871f4e",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 1959"
            },
            "recommended_dosage": {
                "value": "The recommended dose is 150 mg of MPA Injectable Suspension, USP every 3 months (13 weeks) administered by deep, intramuscular (IM) injection in the gluteal or deltoid muscle.",
                "source_name": "FDA prescribing information via DailyMed (MEDROXYPROGESTERONE ACETATE INJECTION, SUSPENSION [PRASCO LABORATORIES])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=987496bf-b4b0-409b-b745-f52ed0871f4e",
                "retrieved": "2026-08-03",
                "quote": "The recommended dose is 150 mg of MPA Injectable Suspension, USP every 3 months (13 weeks) administered by deep, intramuscular (IM) injection in the gluteal or deltoid muscle."
            }
        },
        "spl_setid": "987496bf-b4b0-409b-b745-f52ed0871f4e",
        "spl_title": "MEDROXYPROGESTERONE ACETATE INJECTION, SUSPENSION [PRASCO LABORATORIES]"
    },
    "metoprolol": {
        "molecule": "Metoprolol",
        "facts": {
            "us_initial_approval_year": {
                "value": 1992,
                "source_name": "FDA prescribing information via DailyMed (METOPROLOL TARTRATE (METOPROLOL) TABLET [BRYANT RANCH PREPACK])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=00940cc5-d2eb-4841-9138-de97d7b1c674",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 1992"
            }
        },
        "spl_setid": "00940cc5-d2eb-4841-9138-de97d7b1c674",
        "spl_title": "METOPROLOL TARTRATE (METOPROLOL) TABLET [BRYANT RANCH PREPACK]"
    },
    "norethisterone": {
        "molecule": "Norethisterone",
        "facts": {
            "us_initial_approval_year": {
                "value": 2020,
                "source_name": "FDA prescribing information via DailyMed (ORIAHNN (ELAGOLIX AND ESTRADIOL AND NORETHISTERONE) KIT [ABBVIE INC.])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=99f6eee7-7e52-6999-7eb8-488d06dd1710",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 2020"
            },
            "recommended_dosage": {
                "value": "The recommended dosage of ORIAHNN is: ○ One elagolix 300 mg, estradiol 1 mg, and norethindrone acetate 0.5 mg capsule in the morning (AM), and ○ One elagolix 300 mg capsule in the evening (PM).",
                "source_name": "FDA prescribing information via DailyMed (ORIAHNN (ELAGOLIX AND ESTRADIOL AND NORETHISTERONE) KIT [ABBVIE INC.])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=99f6eee7-7e52-6999-7eb8-488d06dd1710",
                "retrieved": "2026-08-03",
                "quote": "The recommended dosage of ORIAHNN is: ○ One elagolix 300 mg, estradiol 1 mg, and norethindrone acetate 0.5 mg capsule in the morning (AM), and ○ One elagolix 300 mg capsule in the evening (PM)."
            }
        },
        "spl_setid": "99f6eee7-7e52-6999-7eb8-488d06dd1710",
        "spl_title": "ORIAHNN (ELAGOLIX AND ESTRADIOL AND NORETHISTERONE) KIT [ABBVIE INC.]"
    },
    "perindopril": {
        "molecule": "Perindopril",
        "facts": {
            "us_initial_approval_year": {
                "value": 1993,
                "source_name": "FDA prescribing information via DailyMed (PERINDOPRIL ERBUMINE TABLET [AUROBINDO PHARMA LIMITED])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=87768fbf-7c63-47da-8925-0316f343d6ef",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 1993"
            }
        },
        "spl_setid": "87768fbf-7c63-47da-8925-0316f343d6ef",
        "spl_title": "PERINDOPRIL ERBUMINE TABLET [AUROBINDO PHARMA LIMITED]"
    },
    "prasugrel": {
        "molecule": "Prasugrel",
        "facts": {
            "us_initial_approval_year": {
                "value": 2009,
                "source_name": "FDA prescribing information via DailyMed (PRASUGREL TABLET, FILM COATED [APOTEX CORP.])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=f51e64e0-f556-65d0-a876-fb709aaeefea",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 2009"
            }
        },
        "spl_setid": "f51e64e0-f556-65d0-a876-fb709aaeefea",
        "spl_title": "PRASUGREL TABLET, FILM COATED [APOTEX CORP.]"
    },
    "ramipril": {
        "molecule": "Ramipril",
        "facts": {
            "us_initial_approval_year": {
                "value": 1991,
                "source_name": "FDA prescribing information via DailyMed (RAMIPRIL CAPSULE [BRYANT RANCH PREPACK])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3806abdc-6aec-4252-bd79-e2c115b849aa",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 1991"
            }
        },
        "spl_setid": "3806abdc-6aec-4252-bd79-e2c115b849aa",
        "spl_title": "RAMIPRIL CAPSULE [BRYANT RANCH PREPACK]"
    },
    "riociguat": {
        "molecule": "Riociguat",
        "facts": {
            "us_initial_approval_year": {
                "value": 2013,
                "source_name": "FDA prescribing information via DailyMed (ADEMPAS (RIOCIGUAT) TABLET, FILM COATED [BAYER HEALTHCARE PHARMACEUTICALS INC.])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7b57509a-3d5d-41d4-8fed-1471e26372a3",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 2013"
            },
            "recommended_dosage": {
                "value": "The recommended starting dosage is 1 mg taken 3 times a day.",
                "source_name": "FDA prescribing information via DailyMed (ADEMPAS (RIOCIGUAT) TABLET, FILM COATED [BAYER HEALTHCARE PHARMACEUTICALS INC.])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=7b57509a-3d5d-41d4-8fed-1471e26372a3",
                "retrieved": "2026-08-03",
                "quote": "The recommended starting dosage is 1 mg taken 3 times a day."
            }
        },
        "spl_setid": "7b57509a-3d5d-41d4-8fed-1471e26372a3",
        "spl_title": "ADEMPAS (RIOCIGUAT) TABLET, FILM COATED [BAYER HEALTHCARE PHARMACEUTICALS INC.]"
    },
    "rosuvastatin": {
        "molecule": "Rosuvastatin",
        "facts": {
            "us_initial_approval_year": {
                "value": 2003,
                "source_name": "FDA prescribing information via DailyMed (ROSUVASTATIN CALCIUM TABLET, FILM COATED [HEC PHARM USA INC.])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=568a782b-1621-5e59-e063-6294a90a7fef",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 2003"
            },
            "recommended_dosage": {
                "value": "The recommended dosage of Rosuvastatin Tablets depends on a patient’s indication for usage, LDL-C, and individual risk for CV events.",
                "source_name": "FDA prescribing information via DailyMed (ROSUVASTATIN CALCIUM TABLET, FILM COATED [HEC PHARM USA INC.])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=568a782b-1621-5e59-e063-6294a90a7fef",
                "retrieved": "2026-08-03",
                "quote": "The recommended dosage of Rosuvastatin Tablets depends on a patient’s indication for usage, LDL-C, and individual risk for CV events."
            }
        },
        "spl_setid": "568a782b-1621-5e59-e063-6294a90a7fef",
        "spl_title": "ROSUVASTATIN CALCIUM TABLET, FILM COATED [HEC PHARM USA INC.]"
    },
    "sacubitril + valsartan": {
        "molecule": "Sacubitril + Valsartan",
        "facts": {
            "us_initial_approval_year": {
                "value": 2015,
                "source_name": "FDA prescribing information via DailyMed (ENTRESTO (SACUBITRIL AND VALSARTAN) TABLET, FILM COATED ENTRESTO (SACUBITRIL AND VALSARTAN) PELLET [NOVARTIS PHARMACEUTICALS CORPORATION])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=000dc81d-ab91-450c-8eae-8eb74e72296f",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 2015"
            },
            "recommended_dosage": {
                "value": "The recommended starting dosage for adults is 49 mg/51 mg orally twice daily.",
                "source_name": "FDA prescribing information via DailyMed (ENTRESTO (SACUBITRIL AND VALSARTAN) TABLET, FILM COATED ENTRESTO (SACUBITRIL AND VALSARTAN) PELLET [NOVARTIS PHARMACEUTICALS CORPORATION])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=000dc81d-ab91-450c-8eae-8eb74e72296f",
                "retrieved": "2026-08-03",
                "quote": "The recommended starting dosage for adults is 49 mg/51 mg orally twice daily."
            }
        },
        "spl_setid": "000dc81d-ab91-450c-8eae-8eb74e72296f",
        "spl_title": "ENTRESTO (SACUBITRIL AND VALSARTAN) TABLET, FILM COATED ENTRESTO (SACUBITRIL AND VALSARTAN) PELLET [NOVARTIS PHARMACEUTICALS CORPORATION]"
    },
    "saxagliptin": {
        "molecule": "Saxagliptin",
        "facts": {
            "us_initial_approval_year": {
                "value": 2010,
                "source_name": "FDA prescribing information via DailyMed (SAXAGLIPTIN AND METFORMIN TABLET, FILM COATED, EXTENDED RELEASE [MYLAN PHARMACEUTICALS INC.])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=cbf8677c-cafe-48bc-8844-0cc6547886bd",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 2010"
            }
        },
        "spl_setid": "cbf8677c-cafe-48bc-8844-0cc6547886bd",
        "spl_title": "SAXAGLIPTIN AND METFORMIN TABLET, FILM COATED, EXTENDED RELEASE [MYLAN PHARMACEUTICALS INC.]"
    },
    "semaglutide (wegovy)": {
        "molecule": "Semaglutide (Wegovy)",
        "facts": {
            "us_initial_approval_year": {
                "value": 2017,
                "source_name": "FDA prescribing information via DailyMed (WEGOVY (SEMAGLUTIDE) INJECTION, SOLUTION WEGOVY (SEMAGLUTIDE) TABLET [NOVO NORDISK PHARMACEUTICAL INDUSTRIES, LP])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ee06186f-2aa3-4990-a760-757579d8f77b",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 2017"
            }
        },
        "spl_setid": "ee06186f-2aa3-4990-a760-757579d8f77b",
        "spl_title": "WEGOVY (SEMAGLUTIDE) INJECTION, SOLUTION WEGOVY (SEMAGLUTIDE) TABLET [NOVO NORDISK PHARMACEUTICAL INDUSTRIES, LP]"
    },
    "semaglutide (injectable)": {
        "molecule": "Semaglutide (injectable)",
        "facts": {
            "us_initial_approval_year": {
                "value": 2017,
                "source_name": "FDA prescribing information via DailyMed (WEGOVY (SEMAGLUTIDE) INJECTION, SOLUTION WEGOVY (SEMAGLUTIDE) TABLET [NOVO NORDISK PHARMACEUTICAL INDUSTRIES, LP])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ee06186f-2aa3-4990-a760-757579d8f77b",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 2017"
            }
        },
        "spl_setid": "ee06186f-2aa3-4990-a760-757579d8f77b",
        "spl_title": "WEGOVY (SEMAGLUTIDE) INJECTION, SOLUTION WEGOVY (SEMAGLUTIDE) TABLET [NOVO NORDISK PHARMACEUTICAL INDUSTRIES, LP]"
    },
    "semaglutide (oral)": {
        "molecule": "Semaglutide (oral)",
        "facts": {
            "us_initial_approval_year": {
                "value": 2017,
                "source_name": "FDA prescribing information via DailyMed (WEGOVY (SEMAGLUTIDE) INJECTION, SOLUTION WEGOVY (SEMAGLUTIDE) TABLET [NOVO NORDISK PHARMACEUTICAL INDUSTRIES, LP])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=ee06186f-2aa3-4990-a760-757579d8f77b",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 2017"
            }
        },
        "spl_setid": "ee06186f-2aa3-4990-a760-757579d8f77b",
        "spl_title": "WEGOVY (SEMAGLUTIDE) INJECTION, SOLUTION WEGOVY (SEMAGLUTIDE) TABLET [NOVO NORDISK PHARMACEUTICAL INDUSTRIES, LP]"
    },
    "sitagliptin": {
        "molecule": "Sitagliptin",
        "facts": {
            "us_initial_approval_year": {
                "value": 2012,
                "source_name": "FDA prescribing information via DailyMed (SITAGLIPTIN AND METFORMIN HYDROCHLORIDE TABLET, FILM COATED, EXTENDED RELEASE [PAR HEALTH USA, LLC])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=43e3b1c9-3cbd-8dc3-e063-6394a90a10a2",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 2012"
            }
        },
        "spl_setid": "43e3b1c9-3cbd-8dc3-e063-6394a90a10a2",
        "spl_title": "SITAGLIPTIN AND METFORMIN HYDROCHLORIDE TABLET, FILM COATED, EXTENDED RELEASE [PAR HEALTH USA, LLC]"
    },
    "spironolactone": {
        "molecule": "Spironolactone",
        "facts": {
            "us_initial_approval_year": {
                "value": 1960,
                "source_name": "FDA prescribing information via DailyMed (SPIRONOLACTONE TABLET, COATED [PD-RX PHARMACEUTICALS, INC.])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=73564b3d-8ede-4008-b75c-1277153b5bb6",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 1960"
            }
        },
        "spl_setid": "73564b3d-8ede-4008-b75c-1277153b5bb6",
        "spl_title": "SPIRONOLACTONE TABLET, COATED [PD-RX PHARMACEUTICALS, INC.]"
    },
    "teriparatide": {
        "molecule": "Teriparatide",
        "facts": {
            "us_initial_approval_year": {
                "value": 1987,
                "source_name": "FDA prescribing information via DailyMed (FORTEO (TERIPARATIDE) INJECTION, SOLUTION [ELI LILLY AND COMPANY])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=aae667c5-381f-4f92-93df-2ed6158d07b0",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 1987"
            },
            "recommended_dosage": {
                "value": "The recommended dosage is 20 mcg per dose given subcutaneously once a day.",
                "source_name": "FDA prescribing information via DailyMed (FORTEO (TERIPARATIDE) INJECTION, SOLUTION [ELI LILLY AND COMPANY])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=aae667c5-381f-4f92-93df-2ed6158d07b0",
                "retrieved": "2026-08-03",
                "quote": "The recommended dosage is 20 mcg per dose given subcutaneously once a day."
            }
        },
        "spl_setid": "aae667c5-381f-4f92-93df-2ed6158d07b0",
        "spl_title": "FORTEO (TERIPARATIDE) INJECTION, SOLUTION [ELI LILLY AND COMPANY]"
    },
    "ticagrelor": {
        "molecule": "Ticagrelor",
        "facts": {
            "us_initial_approval_year": {
                "value": 2011,
                "source_name": "FDA prescribing information via DailyMed (TICAGRELOR TABLET, FILM COATED [REDPHARM DRUG])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=557351f1-47b7-216d-e063-6394a90afb51",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 2011"
            }
        },
        "spl_setid": "557351f1-47b7-216d-e063-6394a90afb51",
        "spl_title": "TICAGRELOR TABLET, FILM COATED [REDPHARM DRUG]"
    },
    "tirzepatide": {
        "molecule": "Tirzepatide",
        "facts": {
            "us_initial_approval_year": {
                "value": 2022,
                "source_name": "FDA prescribing information via DailyMed (MOUNJARO (TIRZEPATIDE) INJECTION, SOLUTION [A-S MEDICATION SOLUTIONS])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0818426a-53eb-4db7-9609-bbae1e7a3964",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 2022"
            },
            "recommended_dosage": {
                "value": "The recommended starting dosage is 2.5 mg injected subcutaneously once weekly.",
                "source_name": "FDA prescribing information via DailyMed (MOUNJARO (TIRZEPATIDE) INJECTION, SOLUTION [A-S MEDICATION SOLUTIONS])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0818426a-53eb-4db7-9609-bbae1e7a3964",
                "retrieved": "2026-08-03",
                "quote": "The recommended starting dosage is 2.5 mg injected subcutaneously once weekly."
            }
        },
        "spl_setid": "0818426a-53eb-4db7-9609-bbae1e7a3964",
        "spl_title": "MOUNJARO (TIRZEPATIDE) INJECTION, SOLUTION [A-S MEDICATION SOLUTIONS]"
    },
    "tirzepatide (mounjaro)": {
        "molecule": "Tirzepatide (Mounjaro)",
        "facts": {
            "us_initial_approval_year": {
                "value": 2022,
                "source_name": "FDA prescribing information via DailyMed (MOUNJARO (TIRZEPATIDE) INJECTION, SOLUTION [A-S MEDICATION SOLUTIONS])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0818426a-53eb-4db7-9609-bbae1e7a3964",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 2022"
            },
            "recommended_dosage": {
                "value": "The recommended starting dosage is 2.5 mg injected subcutaneously once weekly.",
                "source_name": "FDA prescribing information via DailyMed (MOUNJARO (TIRZEPATIDE) INJECTION, SOLUTION [A-S MEDICATION SOLUTIONS])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=0818426a-53eb-4db7-9609-bbae1e7a3964",
                "retrieved": "2026-08-03",
                "quote": "The recommended starting dosage is 2.5 mg injected subcutaneously once weekly."
            }
        },
        "spl_setid": "0818426a-53eb-4db7-9609-bbae1e7a3964",
        "spl_title": "MOUNJARO (TIRZEPATIDE) INJECTION, SOLUTION [A-S MEDICATION SOLUTIONS]"
    },
    "ulipristal acetate (5 mg)": {
        "molecule": "Ulipristal acetate (5 mg)",
        "facts": {
            "us_initial_approval_year": {
                "value": 2010,
                "source_name": "FDA prescribing information via DailyMed (ELLA (ULIPRISTAL ACETATE) TABLET [PMI BRANDED PHARMACEUTICALS, INC.])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=2bf93d23-cddd-4613-9066-5b5fa090404b",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 2010"
            }
        },
        "spl_setid": "2bf93d23-cddd-4613-9066-5b5fa090404b",
        "spl_title": "ELLA (ULIPRISTAL ACETATE) TABLET [PMI BRANDED PHARMACEUTICALS, INC.]"
    },
    "valsartan": {
        "molecule": "Valsartan",
        "facts": {
            "us_initial_approval_year": {
                "value": 1998,
                "source_name": "FDA prescribing information via DailyMed (VALSARTAN AND HYDROCHLOROTHIAZIDE TABLET, FILM COATED [SCIEGEN PHARMACEUTICALS, INC.])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=17362ff8-07bb-42c6-a100-8adb93be0348",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 1998"
            }
        },
        "spl_setid": "17362ff8-07bb-42c6-a100-8adb93be0348",
        "spl_title": "VALSARTAN AND HYDROCHLOROTHIAZIDE TABLET, FILM COATED [SCIEGEN PHARMACEUTICALS, INC.]"
    },
    "vericiguat": {
        "molecule": "Vericiguat",
        "facts": {
            "us_initial_approval_year": {
                "value": 2021,
                "source_name": "FDA prescribing information via DailyMed (VERQUVO (VERICIGUAT) TABLET, FILM COATED [MERCK SHARP & DOHME LLC])",
                "source_url": "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=17056d73-1b1b-4bf2-9c07-b7a9367f0d6d",
                "retrieved": "2026-08-03",
                "quote": "Initial U.S. Approval: 2021"
            }
        },
        "spl_setid": "17056d73-1b1b-4bf2-9c07-b7a9367f0d6d",
        "spl_title": "VERQUVO (VERICIGUAT) TABLET, FILM COATED [MERCK SHARP & DOHME LLC]"
    }
}

UNMATCHED = [
    [
        "Atosiban",
        "no FDA label found"
    ],
    [
        "Biphasic 30/70",
        "no FDA label found"
    ],
    [
        "Bisoprolol",
        "label found but no extractable pattern"
    ],
    [
        "Candesartan",
        "label found but no extractable pattern"
    ],
    [
        "Cetrorelix",
        "label found but no extractable pattern"
    ],
    [
        "Conjugated equine estrogens",
        "no FDA label found"
    ],
    [
        "Domperidone",
        "label found but no extractable pattern"
    ],
    [
        "Estradiol valerate",
        "label found but no extractable pattern"
    ],
    [
        "Ethinylestradiol + Cyproterone acetate",
        "no FDA label found"
    ],
    [
        "Ethinylestradiol + Desogestrel",
        "no FDA label found"
    ],
    [
        "Ethinylestradiol + Drospirenone",
        "no FDA label found"
    ],
    [
        "Ethinylestradiol + Gestodene",
        "no FDA label found"
    ],
    [
        "Ethinylestradiol + Levonorgestrel",
        "no FDA label found"
    ],
    [
        "Felodipine",
        "label found but no extractable pattern"
    ],
    [
        "Gemfibrozil",
        "label found but no extractable pattern"
    ],
    [
        "Glibenclamide (Glyburide)",
        "no FDA label found"
    ],
    [
        "Human chorionic gonadotropin",
        "label found but no extractable pattern"
    ],
    [
        "Hydroxyprogesterone caproate",
        "label found but no extractable pattern"
    ],
    [
        "Levonorgestrel IUS",
        "no FDA label found"
    ],
    [
        "Mexiletine",
        "label found but no extractable pattern"
    ],
    [
        "NPH / Isophane",
        "no FDA label found"
    ],
    [
        "Prazosin",
        "label found but no extractable pattern"
    ],
    [
        "Regular (soluble) insulin",
        "no FDA label found"
    ],
    [
        "Tibolone",
        "no FDA label found"
    ],
    [
        "Vildagliptin",
        "no FDA label found"
    ]
]
